config/routes.rb
Rails.application.routes.draw do
  
  resources :registered_applications

  devise_for :users
  

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
 end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registeredapplications = RegisteredApplication.all
  end

  def show
    @registeredapplication = RegisteredApplication.find (params[:id])
  end

  def new
    @registeredapplication = RegisteredApplication.new
  end

  def edit
    @registeredapplication = RegisteredApplication.find(params[:id])
  end

  def create 
   @registeredapplication = RegisteredApplication.new(params.require(:registeredapplication).permit(:name, :url))
   if @registeredapplication.save
    flash[:notice] = "Your masterpiece was saved."
    redirect_to @registeredapplication
   else 
    flash[:error] = "Oops there was an error saving, please try save again."
    render :new
   end 
  end 

  def update 
    @registeredapplication = RegisteredApplication.find(params[:id])
     if @registeredapplication.update_attributes(params.require(:registeredapplication).permit(:name, :url))
       flash[:notice] = "Post was updated."
       redirect_to @registeredapplication
     else
       flash[:error] = "There was an error saving the application. Please try again."
       render :edit
  end 
end 

  def read
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <ul class="nav nav-tabs">
        <% if current_user %>
          <li><%= link_to "Blocmetrics", registered_applications_path %></li>
        <% else %>
          <li><%= link_to "Blocmetrics", root_path %></li>
        <% end %>
          <li><%= link_to "About", about_path %></li>
        <div class="nav navbar-nav navbar-right">
          <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.email %>!<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                </ul>
              </li>
            <% else %>
              <%= link_to "Log In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
        </div>   
    </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= yield %>
  </div>
  <%= yield :charts_js %>
</body>
</html>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplications#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/edit.html.erb
<h1>New Registered Application </h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Registered Applications </p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @registeredapplication do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter Application title" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, rows: 1, class: 'form-control', placeholder: "Enter url here" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/registered_applications/index.html.erb
<h1>All Registered Applications</h1>
<% @registeredapplications.each do |registeredapplication| %>
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to registeredapplication.name, registeredapplication %>
       </h4>
     </div>
   </div>
<% end %>

app/views/registered_applications/new.html.erb
<<h1>New Registered Application </h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Registered Applications </p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @registeredapplication do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter Application title" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, rows: 1, class: 'form-control', placeholder: "Enter url here" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/registered_applications/read.html.erb
<h1>RegisteredApplications#read</h1>
<p>Find me in app/views/registered_applications/read.html.erb</p>

app/views/registered_applications/show.html.erb
<div class="jumbotron">
  <h1 align="center"><%= @registeredapplication.name %></h1> 
  <p align="center"><a href="<%= @registeredapplication.url %>"><%= @registeredapplication.url %></a></p> 
</div>


<%= link_to 'Edit This Application', edit_registered_application_path %> |
<%= link_to 'Back To Applications', registered_applications_path %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 align="center">Blocmetrics</h1> 
    <p align="center">Track events from multiple applications</p> 
  </div>
</div>
<div class="container" align="center">
  <div "col-lg-4">
  <p><%= button_to "Sign Up", new_user_registration_path, :class => "btn btn-lg btn-primary", :style => "center", :method => :get %></p>
  </div>
  <div "col-lg-4">
  <p><%= button_to "Log In", new_user_session_path, :class => "btn btn-lg btn-primary", :method => :get %></p>
  </div>
</div>